import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import CheckboxAnimated from '../components/checkbox'
import { VStack } from '@chakra-ui/react'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Whattodo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
      <Navbar />
      <CheckboxAnimated />
      <footer className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-cyan-600">Created by Firelinkshrine</footer>
      </VStack>
    </div>
  )
}

export default Home
