import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import CheckboxAnimated from '../components/checkbox'
import { VStack } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Whattodo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
      <Navbar />
      <CheckboxAnimated />
      </VStack>
    </div>
  )
}

export default Home
